version: '3.5'

services:
  keystore:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: ${ELK_VERSION}
    command: bash /home/oprabin/elk-stack-setup-project/elk-deployment-with-security/setup/setup-keystore.sh
    user: "0"
    volumes:
      - /home/oprabin/elk-stack-setup-project/elk-deployment-with-security/secrets:/secrets
      - /home/oprabin/elk-stack-setup-project/elk-deployment-with-security/setup/:/setup/
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
  certs:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: ${ELK_VERSION}
    command: bash /home/oprabin/elk-stack-setup-project/elk-deployment-with-security/setup/setup-certs.sh
    user: "0"
    volumes:
      - /home/oprabin/elk-stack-setup-project/elk-deployment-with-security/secrets:/secrets
      - /home/oprabin/elk-stack-setup-project/elk-deployment-with-security/setup/:/setup/
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}